name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: ./soen341-frontend/package-lock.json 
      - run: node --version
      - run: npm install
      - run: npm ci
        working-directory: ./soen341-frontend
      - run: npm test
        working-directory: ./soen341-frontend