name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm --version
      - run: echo "running npm ci"
      - run: npm install
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      - name: unit test
        uses: actions/checkout@v4

      - name: Install dependencies (if applicable)
        run: |
          if [ -f package.json ]; then npm install; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f pom.xml ]; then mvn install; fi
      - name: Link to CI with multiple empty tests
        run: |
          mkdir -p tests
          echo "test('Empty test 1', () => { expect(true).toBe(true); });" > tests/placeholder1.test.js
          echo "test('Empty test 2', () => { expect(true).toBe(true); });" > tests/placeholder2.test.js
          mkdir -p test_files
          echo "running unit tests"
          npm test
          echo "import org.junit.jupiter.api.Test; import static org.junit.jupiter.api.Assertions.*; class PlaceholderTest1 { @Test void testPlaceholder1() { assertTrue(true); } }" > test_files/PlaceholderTest1.java
          echo "import org.junit.jupiter.api.Test; import static org.junit.jupiter.api.Assertions.*; class PlaceholderTest2 { @Test void testPlaceholder2() { assertTrue(true); } }" > test_files/PlaceholderTest2.java
          echo "Tests will be added in future sprints. CI is set up."