name: Run Unit Tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          if [ -f package.json ]; then npm install; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f pom.xml ]; then mvn install; fi

      - name: Run unit tests
        run: npm test